# -*- coding: utf-8 -*-
"""
/***************************************************************************
 splitByChainage
                                 A QGIS plugin
 split linestrings by chainage
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-09-09
        copyright            : (C) 2021 by drew
        email                : drew.bennett@ptsinternational.co.uk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'drew'
__date__ = '2021-09-09'
__copyright__ = '(C) 2021 by drew'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load splitByChainage class from file splitByChainage.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ptsToolsPlugin import ptsToolsPlugin
    return ptsToolsPlugin()
